sonar.host.url=http://localhost:9000
sonar.token=sqb_c499c8e531dd33ae9812cdb134f2e4b3592948e9
sonar.projectKey=next-image-package
sonar.projectName=next-export-optimize-svg-images
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**, **/example/**, **/.scannerwork/**, **/.git/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
